start_experiment:
  description: Begins recording an experiment
  fields:
    entity_id:
      description: Name(s) of the entities
      example: "sensor.aircon_efficiency"
    fan_speed:
      description: Speed setting of AC fan
      example: 5